name: CI code quality check

on:
  push:
    branches:
      - '*-hotfix-**'
      - '*-fix-**'
      - '*-bugfix-**'
      - '*-feature-**'
      - '*-enhance-**'
      - '*-refactor-**'
      - '*-chore-**'
      - '*-test-**'
      - '*-ci-**'
      - '*-build-**'
      - '*-deps-**'
      - '*-style-**'
      - '*-docs-**'
      - '*-perf-**'
      - '*-i18n-**'
      - '*-revert-**'
      - '*-config-**'
      - '*-lint-**'

jobs:
  test_commit_validity:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

      - name: Build project
        run: npm run build